spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testes-unitarios
    username: postgres
    password: aluno
    driver: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update